# Generated by Django 2.1.5 on 2019-01-29 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_parametros'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parametros',
            new_name='Parametrosss',
        ),
    ]
