# Generated by Django 2.1.5 on 2019-01-29 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190129_1831'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parametrosss',
            new_name='Parametro',
        ),
    ]
